<?php
$this->title = "Add New HO |";
$this->headTitle($this->title);

echo $this->headScript()->appendFile($this->baseUrl('/javascripts/jquery-ui-1.8.16.custom.min.js'));
echo $this->headLink()->prependStylesheet($this->baseUrl('/css/ui-lightness/jquery-ui-1.8.10.custom.css'));
?>
<form method="post" action="<?php echo $this->url(); ?>" enctype="application/x-www-form-urlencoded" id="HO">
	<dl class="zend_form">
		<dt id="HandOffTitle-label">
			<label class="required" for="HandOffTitle">Handoff Title</label>
		</dt>
		<dd id="HandOffTitle-element">
			<input type="text" maxlength="50" size="40" value="<?php echo $this->form->HandOffTitle->getValue(); ?>" id="HandOffTitle" name="HandOffTitle">
			<?php if( count($this->form->HandOffTitle->getMessages()) >0 ): ?>
				<ul class="errors">
					<?php foreach($this->form->HandOffTitle->getMessages() as $error): ?>
						<li><?php echo $error; ?></li>
					<?php endforeach;?>
				</ul>
			<?php endif;?>
		</dd>
		<dt id="HandOffStartProject-label">
			<label class="required" for="HandOffStartProject">Handoff Date</label>
		</dt>
		<dd id="HandOffStartProject-element">
			<input type="text" size="20" value="<?php echo $this->form->HandOffStartProject->getValue(); ?>" id="HandOffStartProject" name="HandOffStartProject">
			<?php if( count($this->form->HandOffStartProject->getMessages()) >0 ): ?>
				<ul class="errors">
					<?php foreach($this->form->HandOffStartProject->getMessages() as $error): ?>
						<li><?php echo $error; ?></li>
					<?php endforeach;?>
				</ul>
			<?php endif;?>

		</dd>
		
		<div style="float:left; width:300px">
		<dt id="HandOffSourceLanguageID-label" style="width:180px">
			<label class="required" for="HandOffSourceLanguageID">Handoff Source LanguageID</label>
		</dt>
		
		<dd id="HandOffSourceLanguageID-element" style="float: left;">			
			<div style="width: 250px; height:167px; border: 1px solid #7F9DB9;">
					<select style="width: 250px; height:165px; border: 0px solid white" size="10" id="HandOffSourceLanguageID" name="HandOffSourceLanguageID">
						<?php foreach($this->sourceListlanguage as $language):?>				
							<option label="<?php echo $language->LanguageName; ?>" value="<?php echo $language->LanguageID; ?>"
							<?php if($this->form->HandOffSourceLanguageID->getValue() == $language->LanguageID){  
										echo "selected='selected'";
									}
							?>
							title="you only can select one source LanguageID">
								<?php echo $language->LanguageName; ?>
							</option>
						<?php endforeach; ?>
					</select>
			</div>
			<?php if( count($this->form->HandOffSourceLanguageID->getMessages()) >0 ): ?>
				<ul class="errors">
					<?php foreach($this->form->HandOffSourceLanguageID->getMessages() as $error): ?>
							<li><?php echo $error; ?></li>
						<?php endforeach;?>
				</ul>
			<?php endif;?>
		</dd>
		</div>
		<div  style="float:left; width:300px">
		<dt id="HandOffListTargetLanguageID-label" style="width:180px; margin-left:15px">
			<label class="required" for="HandOffListTargetLanguageID">Handoff Target LanguageID</label>
		</dt>
		<dd id="HandOffListTargetLanguageID-element" style="float: left;">
			<div style="width: 250px; height:167px; overflow:scroll; border: 1px solid #7F9DB9;">
				<?php foreach($this->targetListlanguage as $language):?>				
					<label for="HandOffListTargetLanguageID-<?php echo $language->LanguageID; ?>">
						<input id="HandOffListTargetLanguageID-<?php echo $language->LanguageID; ?>" type="checkbox" value="<?php echo $language->LanguageID; ?>" name="HandOffListTargetLanguageID[]"
							<?php 												
								if($this->form->HandOffListTargetLanguageID->getValue() !=""){
									foreach( $this->form->HandOffListTargetLanguageID->getValue() as $targetLanguage){
										if($targetLanguage == $language->LanguageID){
											echo "checked='checked'";
										}
									}
								}
							?>
						>
						<?php echo $language->LanguageName; ?>
					</label>
					<br/>
				<?php endforeach; ?>
			</div>			
			<?php if( count($this->form->HandOffListTargetLanguageID->getMessages()) >0 ): ?>
					<ul class="errors">
						<?php foreach($this->form->HandOffListTargetLanguageID->getMessages() as $error): ?>
							<li><?php echo $error; ?></li>
						<?php endforeach;?>
					</ul>
			<?php endif;?>
		</dd>
		</div>
		<dt id="HandOffInstruction-label">
			<label class="required" for="HandOffInstruction">Handoff Instruction</label>
		</dt>
		<dd id="HandOffInstruction-element" style="clear:left; margin-left:0px">
			<?php echo $this->partial('/partials/_editor.phtml', array("webeditordata" => $this->form->content->getValue()))?>
			<?php if( count($this->form->content->getMessages()) >0 ): ?>
				<ul class="errors">
					<?php foreach($this->form->content->getMessages() as $error): ?>
						<li><?php echo $error; ?></li>
					<?php endforeach;?>
				</ul>
			<?php endif;?>

		</dd>
		<dd id="hoaddlistbuttonaction">
			
			<input type="submit" value="<?php echo $this->SAVE_UPLOAD; ?>" id="saveuploadlaterbutton" name="action">	
			<input type="submit" value="<?php echo $this->SAVE_UPLOAD_LATER; ?>" id="submitbutton" name="action">			
			<input type="submit" value="<?php echo $this->CANCEL; ?>" id="cancelbutton" name="action">
		</dd>
		<input type="hidden" id="HandOffID" value="0" name="HandOffID">
		<input type="hidden" id="UserID" value="0" name="UserID">		
		<input type="hidden" id="HandOffTotalNumberOfUploadFiles" value="0" name="HandOffTotalNumberOfUploadFiles"><?php echo $this->form->hash; ?>		
	</dl>
</form>
<script type="text/javascript">
	$(function(){
		$('#HandOffTitle').focus();
		$('#HandOffStartProject').datepicker({
			showOn: "button",
			buttonImage: "<?php echo $this->baseUrl('/images/calendar.gif');?>",
			dateFormat: 'yy-mm-dd',
			buttonImageOnly: true
		});	
	});
</script>