<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle('Bento Localization Portal | Jonckers');
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
<head >
	<?php echo $this->headMeta();?>
	<?php echo $this->headTitle();?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl('/css/style.css'));?>	
	<?php echo $this->headScript()->prependFile($this->baseUrl("/javascripts/jquery-1.6.2.min.js"));?>
</head>
<body>
<div id="page">
	<div id="header">
		<div id="headerright">
			<p style="clear:both; height:36px"/>
			<ul id="nav">
				<li><a href="<?php echo $this->baseUrl('/index/documentation/');?>">Documentation</a> </li>
				<li> | </li>
				<li ><a href="<?php echo $this->baseUrl('/index/contact/');?>">Contact Us</a></li>
				<li>
					<form method="post" action="<?php echo $this->url(); ?>" enctype="application/x-www-form-urlencoded" id="translationLanguage">
						<select name="msmtlanguage" id="msmtlanguage" style="margin-top:-5px">
							<?php foreach(Zend_Registry::get('languages') as $key => $value):?>
							<option value="<?php echo $key;?>" 
								<?php if($_SESSION['msmtlanguage']['language'] == "$key"):?>
									selected="selected"
								<?php endif;?>								
							>
								<?php echo $value;?>								
							</option>
							
							<?php endforeach;?>
						</select>
					</form>
				</li>
			</ul>
		</div>
		<div id="headerimg">
			<a href="http://www.jonckers.com/"><img src="<?php echo $this->baseUrl('/images/logo.jpg');?>" /></a>
		</div>
	</div>
	<br style="clear:both;" />
	<div class="header_img"><img src="<?php echo $this->baseUrl('/images/localization_services_header.jpg');?>" /></div>	

	<?php echo $this->showMenuDependingRole();?>

	<div id="right_content" class="narrowcolumn">	          
		<div>
			<?php echo $this->layout()->content; ?>
		</div>	
	</div>

	<div id="footer">
		&nbsp;
	</div>
</div>
<p class="footertext">&copy; 2011, Jonckers Translation and Engineering. All Rights Reserved. </p>
<script type="text/javascript">
	$(function(){
		$("#msmtlanguage").change(function(){
			<?php 			
			if($_SESSION['msmtlanguage']['showWarningMessage']):?>			
				alert("This is a machine translated page which is provided \"as is\" without warranty.Machine translation may be difficult to understand. Please refer to English pages whenever possible.");
			<?php endif;?>
			$("#translationLanguage").submit();
		});
	});
</script>
</body>
</html>
