<?php
$this->title = "Index Email Template |";
$this->headTitle($this->title);
?>
<form method="post" action="<?php echo $this->url(array('controller' => 'email', 'action' => 'index')); ?>">
	<a href="<?php echo $this->url(array('controller'=>'email',
	'action'=>'add', 'page' => null, "limit"=> null));?>">Add new email template</a>
	<table class="adminlist" border="1px">
		<thead>
			<?php
				// Display pagination control
				echo $this->paginationControl($this->paginator, 'Sliding', '/partials/paginator.phtml', array("colspan" => 5));
			?>
			<tr>				
				<th width="2%">
					EmailTemplateID
				</th>
				<th width="10%">
					EmailTemplateSubject
				</th>
				<th width="5%">
					EmailTemplateStatus
				</th>				
				<th width="5%">
					Active
				</th>		
				<th width="10%">
					&nbsp;
				</th>
			</tr>
		</thead>
		<tfoot>
			<?php
				// Display pagination control
				echo $this->paginationControl($this->paginator, 'Sliding', '/partials/paginator.phtml', array("colspan" => 5));
			?>
		</tfoot>
		<tbody>
			<?php 
				if ( 0 == count($this->resultSet)){
					echo $this->partial('/partials/paginator_nodata.phtml', array("colspan" => 5));
				}				
			?>
			<?php foreach($this->resultSet as $emailtemplate ):?>
			<tr>	
				<td class="center">
					<?php echo $this->escape($emailtemplate->EmailTemplateID);?>
				 </td>
				 <td class="center">
					<?php echo $this->escape($emailtemplate->EmailTemplateSubject);?>
				 </td>
				<td class="center">					
					<?php echo $this->escape($emailtemplate->EmailTemplateStatus);?>				
				</td>
				<td class="center">
					<?php echo $this->escape($emailtemplate->EmailTemplateIsActive);?>				
				</td>
				<td class="center">
					<a href="<?php echo $this->url(array('controller'=>"email", 'action'=> 'viewdetail', 'emailTemplateID'=>$this->escape($emailtemplate->EmailTemplateID),
					'page' => null, "limit"=> null));?>">Details</a> |
					<a href="<?php echo $this->url(array('controller'=>"email", 'action'=> 'edit', 'emailTemplateID'=>$this->escape($emailtemplate->EmailTemplateID),
					'page' => null, "limit"=> null));?>">Edit</a> |
					<a href="<?php echo $this->url(array('controller'=>"email", 'action'=> 'delete', 'emailTemplateID'=>$this->escape($emailtemplate->EmailTemplateID),
					'page' => null, "limit"=> null));?>">Delete</a>
				</td>
			</tr>		
			<?php endforeach;?>
		</tbody>
	</table>