<div style="margin-left:10px">
<h2><?php echo $this->message ?></h2>

<?php if (isset($this->exception)): ?>

<h3>Exception information:</h3>
<p>
  <b>Message:</b> <?php echo $this->exception->getMessage() ?>
</p>
<p>
	<a href="<?php echo $this->baseUrl('/ho/index');?>">Back to Bento Localization Portal</a>	
<p>
<p>
	<a href="<?php echo $this->baseUrl('/auth/index');?>">Login</a>	
<p>
<?php endif ?>
</div>