<?php
$this->title = "Add New User |";
$this->headTitle($this->title);
echo $this->headScript()->appendFile($this->baseUrl('/javascripts/jquery-ui-1.8.10.custom.min.js'));
echo $this->headLink()->prependStylesheet($this->baseUrl('/css/base/jquery.ui.all.css'));
?>
<?php if (isset($this->insertErrorMessage)) :?>
<ul class="errors">
	<li><?php echo $this->insertErrorMessage; ?></li>
</ul>
<?php endif;?>
<?php				
	echo $this->form;
?>

<script>
	$(function() {		
		$('#UserName').focus();
		$( "#JtepmEmail" ).autocomplete({
			source: ["<?php echo join("\", \"", $this->jtepmEmailList); ?>"]
		});
		
		$("#UserIsClient-N").click(function(){		
			$("#JtepmEmail-label").hide();
			$("#JtepmEmail-element").hide();	
		});
		
		if( $("#UserIsClient-N").is(':checked')){
			$("#JtepmEmail-label").hide();
			$("#JtepmEmail-element").hide();	
		}
		
		$("#UserIsClient-Y").click(function(){		
			$("#JtepmEmail-label").show();
			$("#JtepmEmail-element").show();	
		});
		
		$("#UserRootUploadDirectory").focus(function(){
			if($("#UserRootUploadDirectory").val() == "<?php echo Application_Form_User::UPLOAD_DIRECTORY_LABEL?>"){
				$("#UserRootUploadDirectory").val("");
			}
		});
		
		$("#User").submit(function(){
			if($("#UserRootUploadDirectory").val() == "<?php echo Application_Form_User::UPLOAD_DIRECTORY_LABEL?>"){
				$("#UserRootUploadDirectory").val("");
			}
		});
	});
</script>